---
# file: group_vars/all
# file contains shared variables for all playbooks

# DESIGN NOTE: We are minimizing the number of variables declared here!
# Use the debug.yml page to name & test that variables are injected correctly
# Please DO DRY your code with variables
# Please do NOT create variables for things that are really hardcoded.

# documentation of source for troubleshooting
playbook_source: "https://github.com/digitalrebar/kompos8"

# show variables during runs
debug: true

# common paths
bin_dir: /usr/local/bin-
config_dir: /etc/kubernetes
log_dir: /var/log/kubernetes

# locations and hashs of downloads
sources:
  download_url: "https://storage.googleapis.com/kubernetes-release/release/{{ k8s.version }}/bin/linux/amd64"
  v1.2.5:
    apiserver: fbe8296ad4b194c06f6802a126d35cd2887dc1aded308d4da2b580f270412b33
    kubectl: 5526a496a84701015485e32c86486e2f23599f7a865164f546e619c6a62f7f19
    kubelet: cd15b929f0190876216f397c2c6e7aa8c08d3b047fd90b4980cd68c8f4896211
  v1.3.3:
    apiserver: a92a74a0d3f7d02d01ac2c8dfb5ee2e97b0485819e77b2110eb7c6b7c782478c
