---
# file: group_vars/all
# file contains shared variables for all playbooks

# system user account for install
user:
  name: kube
  comment: "Kubernetes user"
  shell: /sbin/nologin
  system: yes
  group: "{{ kube_cert_group }}"
  createhome: no

# Version of Kubernetes to use (see sources.yml)
kube_version: v1.2.4

# This is the group that the cert creation scripts chgrp the
# cert files to. Not really changable...
kube_cert_group: kube-cert

# Cluster Loglevel configuration
kube_log_level: 2

# Directory where the binaries will be installed
bin_dir: /usr/local/bin
kube_bin_dir: /kubernetes/bin

# Where the binaries will be downloaded.
# Note: ensure that you've enough disk space (about 1G)
local_release_dir: "/tmp/releases"

# This directory is where all the additional scripts go
# that Kubernetes normally puts in /srv/kubernetes.
# This puts them in a sane location
kube_script_dir: "{{ bin_dir }}/kubernetes-scripts"

# This directory is where all the additional config stuff goes
# the kubernetes normally puts in /srv/kubernets.
# This puts them in a sane location.
# Editting this value will almost surely break something. Don't
# change it. Things like the systemd scripts are hard coded to
# look in here. Don't do it.
kube_config_dir: /etc/kubernetes

# This is where all the cert scripts and certs will be located
kube_cert_dir: "{{ kube_config_dir }}/ssl"

# This is where all of the bearer tokens will be stored
kube_token_dir: "{{ kube_config_dir }}/tokens"

# This is where to save basic auth file
kube_users_dir: "{{ kube_config_dir }}/users"

# This is where you can drop yaml/json files and the kubelet will run those
# pods on startup
kube_manifest_dir: "{{ kube_config_dir }}/manifests"

# Logging directory (sysvinit systems)
kube_log_dir: "/var/log/kubernetes"

# documentation of source for troubleshooting
playbook_source: "https://github.com/digitalrebar/kompos8"