---
# file: group_vars/all
# file contains shared variables for all playbooks

debug: true

# system user account for install
user:
  name: "{{ k8s.user.name }}"
  comment: "Kubernetes user"
  shell: /sbin/nologin
  system: yes
  group: "{{ k8s.cert_group }}"
  createhome: no

dns:
  setup: false
  server: "8.8.8.8"
  domain: "example.com"

cluster:
  name: "kompos8"
  address: 127.0.0.1
  addresses: []

etcd:
  port: 2379
  addresses: []

# System Wide Defaults (DO NOT USE |default() anywhere - these ARE the defaults!)
k8s:
  apiserver:
    port: 443
    insecure_port: 8080
  # Version of Kubernetes to use (see sources.yml)
  version: "v1.2.4"
  # This is the group that the cert creation scripts chgrp the
  # cert files to. Not really changable...
  cert_group: kube-cert
  # Cluster Loglevel configuration
  log:
    level: 2
    # Logging directory (sysvinit systems)
    dir: "/var/log/kubernetes"
  # Directory where the binaries will be installed
  bin_dir: /usr/local/bin
  # This directory is where all the additional scripts go
  # that Kubernetes normally puts in /srv/kubernetes.
  # This puts them in a sane location
  script_dir: "{{ k8s.bin_dir }}/kubernetes-scripts"
  # This directory is where all the additional config stuff goes
  # the kubernetes normally puts in /srv/kubernets.
  # This puts them in a sane location.
  # Editting this value will almost surely break something. Don't
  # change it. Things like the systemd scripts are hard coded to
  # look in here. Don't do it.
  config_dir: /etc/kubernetes
  # This is where all the cert scripts and certs will be located
  cert_dir: "{{ k8s.config_dir }}/ssl"
  # This is where all of the bearer tokens will be stored
  token_dir: "{{ k8s.config_dir }}/tokens"
  # This is where to save basic auth file
  users_dir: "{{ k8s.config_dir }}/users"
  # This is where you can drop yaml/json files and the kubelet will run those
  # pods on startup
  manifest_dir: "{{ k8s.config_dir }}/manifests"

# Where the binaries will be downloaded.
# Note: ensure that you've enough disk space (about 1G)
local_release_dir: "/tmp/releases"

# documentation of source for troubleshooting
playbook_source: "https://github.com/digitalrebar/kompos8"