---

- file: path="~/.ansible/files" state=directory

- name: Update package management cache (YUM)
  yum: update_cache=yes name='*'
  when: ansible_pkg_mgr == 'yum'

- name: Install packages requirements [SLOW]
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "libselinux-python"
    state: latest
  when: ansible_pkg_mgr == 'yum'

- name: Fetch tarball
  fetch: src="{{ opencontrail_host_kernel_artifact_tar }}" dest="/tmp/.ansible/artifacts/" flat=yes
  delegate_to: "{{ groups['builders'][0] }}"

- name: Copy vrouter tarball
  copy:
    src: "/tmp/.ansible/artifacts/opencontrail-vrouter-{{ opencontrail_host_kernel_tag }}.tgz"
    dest: "~/.ansible/files/opencontrail-vrouter-{{ opencontrail_host_kernel_tag }}.tgz"

- name: Extract vrouter module
  shell: "tar zxf ~/.ansible/files/opencontrail-vrouter-{{ opencontrail_host_kernel_tag }}.tgz --no-overwrite-dir --skip-old-files"
  args:
    chdir: /

- name: Depmod
  command: depmod

# Reduce the vrouter table sizes in order to be able to execute on a 2G VM.
- name: Reduce memory utilization of vrouter
  copy: src=vrouter.conf dest=/etc/modprobe.d
  when: ansible_memtotal_mb|int < 4096

- name: Redhat-style interface configuration
  include: vrouter-redhat.yml
  when: ansible_os_family == "RedHat"

- name: Ubuntu interface configuration
  include: vrouter-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Ensure configuration directory exists
  file: path=/etc/contrail state=directory
