--- 
- debug: msg="Playbook source {{ playbook_source }} "

# debugging variables
- include: debug.yml
  when: debug

- name: Update package management cache (YUM)
  yum: update_cache=yes name='*'
  when: ansible_pkg_mgr == 'yum'

- name: Install packages requirements [SLOW]
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "libselinux-python"
    state: latest
  when: ansible_pkg_mgr == 'yum'

- name: Install packages requirements [SLOW]
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "cgroup-lite"
    state: latest
  when: ansible_pkg_mgr == 'apt'

- name: "Download Docker Executables [SLOW]"
  command: "curl -o /tmp/docker.tgz https://get.docker.com/builds/Linux/x86_64/docker-{{k8s.docker.version}}.tgz"
  args:
    creates: /tmp/docker.tgz

- name: "Untar docker"
  unarchive:
    src: /tmp/docker.tgz
    dest: /tmp
    copy: no
    creates: "/tmp/docker/docker"

- name: Put docker files in place
  shell: "cp -p /tmp/docker/docker* /usr/bin"
  args:
    creates: /usr/bin/docker

- name: install | Write docker initd script
  template: src=docker.initd.j2 dest=/etc/init.d/docker owner=root mode=0755
  when: ansible_service_mgr in ["sysvinit","upstart"] and ansible_os_family == "Debian"
  notify: restart docker

- name: install | Write docker conf script
  template: src=docker.conf.j2 dest=/etc/init/docker.conf owner=root mode=0755
  when: ansible_service_mgr in ["sysvinit","upstart"] and ansible_os_family == "Debian"
  notify: restart docker

- name: install | Write docker default file
  template: src=docker.defaults.j2 dest=/etc/default/docker owner=root mode=0755
  when: ansible_service_mgr in ["sysvinit","upstart"] and ansible_os_family == "Debian"
  notify: restart docker

- name: install | Write docker systemd init file
  template:
    src: "docker.service.j2"
    dest: "/etc/systemd/system/docker.service"
  when: ansible_service_mgr == "systemd"
  notify:
    - reload docker systemd
    - restart docker

- meta: flush_handlers

- name: Enable docker
  service:
    name: docker
    enabled: yes

- name: Get load items
  command: >
    curl -o "/tmp/{{ item }}" "http://192.168.99.100:8091/files/docker/{{item}}"
  with_items: k8s.container_load_list

- name: import load items
  command: >
    docker load -i "/tmp/{{ item }}"
  with_items: k8s.container_load_list
  ignore_errors: true

- name: rm load items
  command: >
    rm -f "/tmp/{{ item }}"
  with_items: k8s.container_load_list

