---

- name: "Kubelet config dir exists"
  file:
    path: "/etc/systemd/system/kubelet.service.d"
    state: directory
    recurse: yes

- name: Set kubelet network options
  template:
    src: kubelet
    dest: "/etc/systemd/system/kubelet.service.d/network.conf"
    owner: root
    group: root
    mode: 0644

