---
- name: Write flannel configuration
  template:
    src: network.json
    dest: /etc/flannel-network.json
    backup: yes

- name: Inject flannel config into etcd
  shell: etcdctl --endpoints {% for host in etcd.addresses %}https://{{ host }}:{{ etcd.port }}{% if not loop.last %},{% endif %}{% endfor %} --cert-file {{ flannel.etcd_cert_file }} --key-file {{ flannel.etcd_key_file }} --ca-file {{ flannel.etcd_ca_file }} set /{{k8s.cluster_name}}/network/config < /etc/flannel-network.json

