---
#
# We ignore errors here, because in general, this is run before docker is installed, but 
# should handle a reset/run if needed.
#
# We should really watch for docker or not to notify.
#
- name: delete default docker bridge
  command: ip link delete docker0
  ignore_errors: yes
  notify: restart docker

- name: restart docker
  command: /bin/true
  ignore_errors: yes
  notify:
    - reload systemd
    - reload docker

- name : reload systemd
  shell: systemctl daemon-reload
  ignore_errors: yes
  when: ansible_service_mgr == "systemd"

- name: reload docker
  service:
    name: docker
    state: restarted
  ignore_errors: yes

