---

- name: "DOWNLOAD DEBUG VAR: Version"
  debug: var=k8s.version
  when: debug

- name: "DOWNLOAD DEBUG VAR: Strict Checksum"
  debug: var=k8s.strict
  when: debug

- name: "DOWNLOAD DEBUG VAR: Version Staged"
  debug: var=k8s.version_stage

- name: "DOWNLOAD DEBUG: Version Passed from Caller"
  debug: var=kube_version

- name: "DOWNLOAD DEBUG VAR: Download Source"
  debug: var=source.url
  when: debug

- name: "DOWNLOAD DEBUG VAR: Component"
  debug: var=kube_component
  when: debug

- name: "DOWNLOAD DEBUG VAR: Checksum"
  debug: var=source.checksum["{{ kube_version | default(k8s.version) }}"]["{{ kube_component }}"]
  when: debug

- name: "Ensure Version Defined (use {{ k8s.version }} if not)"
  set_fact: kube_version="{{ k8s.version }}"
  when: kube_version is not defined

- name: "Ensure Version Set (use {{ k8s.version }} if not)"
  set_fact: kube_version="{{ k8s.version }}"
  when: kube_version == ""

- name: "Download {{ kube_component }} {{ kube_version | default(k8s.version) }} Kubernetes Executable WITHOUT CHECKSUM [SLOW]"
  get_url:
    dest: "{{bin_dir}}/{{ kube_component }}"
    url: "{{ source.url }}/{{ kube_component }}"
    mode: 0755
  when: not k8s.strict|default(true)

- name: "Download {{ kube_component}} {{ kube_version | default(k8s.version) }} Kubernetes Executables [SLOW]"
  get_url:
    dest: "{{bin_dir}}/{{ kube_component }}"
    checksum: "{{ item }}"
    url: "{{ source.url }}/{{ kube_component }}"
    validate_certs: yes
    mode: 0755
  with_items: "{{ vars['source']['checksum'][kube_version | default(k8s.version)][kube_component] }}"
  when: source.checksum["{{kube_version | default(k8s.version)}}"][kube_component] is defined and k8s.strict|default(true)
  ignore_errors: not k8s.strict|default(true)