--- 
- name: Kubernetes API Server Install by RackN 2016
  hosts: all
  tasks:
    - debug: msg="Playbook source {{ playbook_source }} "
    # SHA references
    - include_vars: group_vars/sources.yml
    # debugging variables
    - include: prereqs/debug.yml
      when: debug
    # main script
    #- include: apiserver/main.yml
