--- 
- name: Kubernetes Controller Install by RackN 2016

  hosts: all
  handlers:
    - include: handlers/main.yml
  tasks:
    - debug: msg="Playbook source {{ playbook_source }} "
    # SHA references
    - include_vars: group_vars/sources.yml
    # debugging variables
    - include: prereqs/debug.yml
      when: debug
    # main script
    - include: controller/main.yml
