--- 
- name: Kubernetes Pre-reqs Install by RackN 2016
  hosts: all

  tasks:
    - debug: msg="Playbook source {{ playbook_source }} "

    - include-var: prereqs/vars.yml
    
    # debugging variables
    - include: prereqs/debug.yml
      when: debug

    # primary install
    - include: prereqs/main.yml
