--- 
- name: Kubernetes Proxy Install by RackN 2016

  hosts: all
  handlers:
    - include: handlers/main.yml
  tasks:
    - debug: msg="Playbook source {{ playbook_source }} "
    # SHA references
    - include_vars: group_vars/all.yml
    - include_vars: group_vars/sources.yml
    # debugging variables
    - include: prereqs/debug.yml
      when: debug
    - include: proxy/main.yml
