--- 
- name: Kubernetes Scheduler Install by RackN 2016
  hosts: all
  tasks:
    - debug: msg="Playbook source {{ playbook_source }} "
    # debugging variables
    - include: prereqs/debug.yml
      when: debug
    #- include: scheduler/main.yml
