---

- name: Update package management cache (YUM)
  yum: update_cache=yes name='*'
  when: ansible_pkg_mgr == 'yum'

- name: Install packages requirements [SLOW]
  action:
    module: "{{ ansible_pkg_mgr }}"
    name: "libselinux-python"
    state: latest
  when: ansible_pkg_mgr == 'yum'

- name: "Docker config dir exists"
  file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory
    recurse: yes

- name: Set docker daemon options
  template:
    src: docker
    dest: "/etc/systemd/system/docker.service.d/network_opts.conf"
    owner: root
    group: root
    mode: 0644

