--- 
- debug: msg="Playbook source {{ playbook_source }} "

# debugging variables
- include: debug.yml
  when: debug

- name: "Download Kubernetes Executables [SLOW]"
  get_url:
    dest: "{{bin_dir}}/kube-proxy"
    checksum: "{{ item }}"
    url: "{{ source.url }}/kube-proxy"
    validate_certs: yes
    mode: 0755
  with_items: "{{ vars['source']['checksum'][k8s.version]['kube-proxy'] }}"
  when: source.checksum["{{k8s.version}}"] is defined and k8s.strict|default(true)

- name: install | Write kube-proxy systemd init file
  template:
    src: kube-proxy.service.j2
    dest: /etc/systemd/system/kube-proxy.service
  when: ansible_service_mgr == "systemd"
  notify:
    - reload proxy systemd
    - restart proxy

# reload-systemd
- meta: flush_handlers

- name: Enable proxy
  service:
    name: proxy
    enabled: yes

