---
- name: restart kubelet
  command: /bin/true
  notify:
    - reload systemd
    - reload kubelet

- name: reload systemd
  command: systemctl daemon-reload
  when: ansible_service_mgr == "systemd"

- name: reload kubelet
  service:
    name: kubelet
    state: restarted
