---
- name: Create directory
  file: path=/tmp/.ansible/build/{{ opencontrail_host_kernel_tag }} state=directory

- include: kmod-build-redhat.yml
  when: ansible_os_family == "RedHat"

- include: kmod-build-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: kmod-artifacts.yml
