--- 
- debug: msg="Playbook source {{ playbook_source }} "

# debugging variables
- include: debug.yml
  when: debug

- include: ../shared/tasks/downloader.yml kube_component=kube-controller-manager

- name: install | Write kube-controller systemd init file
  template:
    src: "kube-controller.service.j2"
    dest: "/etc/systemd/system/kube-controller.service"
    backup: yes
  when: ansible_service_mgr == "systemd"
  notify: 
    - reload kube-controller systemd
    - restart kube-controller

- meta: flush_handlers

- name: Enable controller
  service:
    name: kube-controller
    enabled: yes

#GREG: This is wrong, do this instead: sudo systemctl status kube-controller-manager --no-pager

- name: wait for the controller to be running
  wait_for:
    port: "{{ k8s.apiserver.insecure_port }}"
    timeout: 60

