--- 
- debug: msg="Playbook source {{ playbook_source }} "

# debugging variables
- include: debug.yml
  when: debug
# main script

- include: ../shared/tasks/downloader.yml kube_component=kubectl

- name: Copy kubectl bash completion
  copy:
    src: kubectl_bash_completion.sh
    dest: /etc/bash_completion.d/kubectl.sh
  when: ansible_os_family in ["Debian","RedHat"]

- name: restart kubelet
  service:
    name: kubelet
    state: restarted
  changed_when: false
