---
- name: Create install tree
  file:
    path: "{{ opencontrail_host_kernel_install_dir }}/usr/bin"
    state: directory

- name: Create install tree (kmod)
  file:
    path: "{{ opencontrail_host_kernel_install_dir }}/lib/modules/{{ ansible_kernel }}/extra/net"
    state: directory

- name: Install utilities
  command: install -m 755 "production/vrouter/utils/{{ item }}" "{{ opencontrail_host_kernel_install_dir }}/usr/bin"
  args:
    chdir: "{{ opencontrail_host_kernel_build_dir }}"
    creates: "{{ opencontrail_host_kernel_install_dir }}/usr/bin/{{ item }}"
  with_items:
    - dropstats
    - flow
    - mirror
    - mpls
    - nh
    - rt
    - vif
    - vrfstats
    - vrouter
    - vxlan

- name: Install kmod
  command: install kbuild/vrouter.ko "{{ opencontrail_host_kernel_install_dir }}/lib/modules/{{ ansible_kernel }}/extra/net"
  args:
    chdir: "{{ opencontrail_host_kernel_build_dir }}"
    creates: "{{ opencontrail_host_kernel_install_dir }}/lib/modules/{{ ansible_kernel }}/extra/net/vrouter.ko"

- name: Create tarball
  command: tar zcf "{{ opencontrail_host_kernel_artifact_tar }}" .
  args:
    chdir: "{{ opencontrail_host_kernel_install_dir }}"
    creates: "{{ opencontrail_host_kernel_artifact_tar }}"

