--- 
- debug: msg="Playbook source {{ playbook_source }} "

# debugging variables
- include: debug.yml
  when: debug

- name: "Download Kubernetes Executables [SLOW]"
  get_url:
    dest: "{{bin_dir}}/kube-scheduler"
    checksum: "{{ item }}"
    url: "{{ source.url }}/kube-scheduler"
    validate_certs: yes
  with_items: "{{ vars['source']['checksum'][k8s.version]['kube-scheduler'] }}"
    when: source.checksum["{{k8s.version}}"] is defined and k8s.strict|default(true)

- name: install | Write kube-scheduler systemd init file
  template:
    src: "kube-scheduler.service.j2"
    dest: "/etc/systemd/system/kube-scheduler.service"
    backup: yes
  when: ansible_service_mgr == "systemd"
  notify: 
    - reload kube-scheduler systemd
    - restart kube-scheduler

- meta: flush_handlers

- name: Enable scheduler
  service:
    name: kube-scheduler
    enabled: yes

# GREG: This is wrong, do this instead: sudo systemctl status kube-scheduler-manager --no-pager

- name: wait for the scheduler to be running
  wait_for:
    port: "{{ k8s.apiserver.insecure_port }}"
    timeout: 60



