
barclamp:
  name: helm
  display: Helm Kubernetes Instance
  license: "restricted"
  copyright: "RackN, 2016"
  os_support:
    - ubuntu-14.04
    - ubuntu-15.04
    - centos-6.6
    - redhat-6.6
    - centos-7.1-1503
    - redhat-7.1

roles:
  - name: helm
    description: 'Install and start HELM'
    jig: script
    flags:
      - milestone
    requires:
      - k8s-dns
