--- 
- debug: msg="Playbook source {{ playbook_source }} "

# debugging variables
- include: debug.yml
  when: debug

- include: ../shared/tasks/downloader.yml kube_component=kube-scheduler

- name: install | Write kube-scheduler initd script
  template: src=kube-scheduler.initd.j2 dest=/etc/init.d/kube-scheduler owner=root mode=0755
  when: ansible_service_mgr in ["sysvinit","upstart"] and ansible_os_family == "Debian"
  notify: restart kube-scheduler

- name: install | Write kube-scheduler conf script
  template: src=kube-scheduler.conf.j2 dest=/etc/init/kube-scheduler.conf owner=root mode=0755
  when: ansible_service_mgr in ["sysvinit","upstart"] and ansible_os_family == "Debian"
  notify: restart kube-scheduler

- name: install | Write kube-scheduler default file
  template: src=kube-scheduler.defaults.j2 dest=/etc/default/kube-scheduler owner=root mode=0755
  when: ansible_service_mgr in ["sysvinit","upstart"] and ansible_os_family == "Debian"
  notify: restart kube-scheduler

- name: install | Write kube-scheduler systemd init file
  template:
    src: "kube-scheduler.service.j2"
    dest: "/etc/systemd/system/kube-scheduler.service"
    backup: yes
  when: ansible_service_mgr == "systemd"
  notify: 
    - reload kube-scheduler systemd
    - restart kube-scheduler

- meta: flush_handlers

- name: Enable scheduler
  service:
    name: kube-scheduler
    enabled: yes

# GREG: This is wrong, do this instead: sudo systemctl status kube-scheduler-manager --no-pager

- name: wait for the scheduler to be running
  wait_for:
    port: "{{ k8s.apiserver.insecure_port }}"
    timeout: 60



