---

- assert:
    that:
      - "'masters' in groups"
      - "'nodes' in groups"
      - "'gateways' in groups"

- name: Assert that interface facts are defined
  assert:
    that:
      - opencontrail_host_interface is defined
      - opencontrail_host_ipaddr is defined
      - opencontrail_host_address is defined
      - opencontrail_host_gateway is defined

- name: Assert that cluster dependent vars are defined
  assert:
    that:
      - opencontrail_all_service_addresses is defined
      - opencontrail_all_kube_config_dir is defined

- name: VRouter log directory
  file: path="/var/log/contrail" state=directory

- name: VRouter agent configuration
  template: src=contrail-vrouter-agent.conf.gateway.j2 dest=/etc/contrail/contrail-vrouter-agent.conf
  notify:
    - restart contrail-vrouter-agent

- name: Redhat-sytle interface configuration
  include: gateway-redhat.yml
  when: ansible_os_family == "RedHat"

- name: Ubuntu interface configuration
  include: gateway-ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Create vrouter agent service
  template: src=contrail-vrouter-agent.service.j2 dest=/etc/systemd/system/contrail-vrouter-agent.service
  notify:
    - reload systemd
  when: not (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 15)

- name: Enable vhost0 interface
  command: ifup vhost0

- name: Docker image ids (gateways)
  command: docker images -q "{{ item }}"
  with_items:
    - "opencontrail/vrouter-agent:{{ opencontrail_all_release }}"
  register: _docker_image_ids
  always_run: true

- name: Pull docker images (gateways)
  command: docker pull "{{ item.item }}"
  with_items: _docker_image_ids.results
  when: not item.stdout

- name: Start vrouter agent
  service: name=contrail-vrouter-agent enabled=yes state=started
