---
driver:
  name: vagrant

driver_config:
  customize:
    memory: 4096
  network:
    - ["forwarded_port", {guest: 80, host: 9000, auto_correct: true}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1

suites:
  - name: standalone
    run_list:
      - recipe[dcos]
    attributes:
      dcos:
        roles:
          - 'master'
          - 'slave'
        quorum: 1
        zookeeper_cluster_size: 1
        master_lb: '127.0.0.1'
        exhibitor:
          web_ui_port: 8181
          shared_fs_configdir: '/var/run/exhibitor'
  - name: master
    run_list:
      - recipe[dcos]
    attributes:
      dcos:
        roles:
          - 'master'
        quorum: 1
        zookeeper_cluster_size: 1
        master_lb: '127.0.0.1'
        exhibitor:
          web_ui_port: 8181
          shared_fs_configdir: '/var/run/exhibitor'
