---
# APL v2 Licensed.  Copyright RackN 2016
# Provides quick way to validate that all required variables are present

- name: "Debug On? YES!"
  debug: msg='!!!!! WARNING - DEBUG ON - DISABLE FOR PRODUCTION !!!!!'

- name: "VAR: Account"
  debug: var=k8s.account

- name: "VAR: Version"
  debug: var=k8s.version

- name: "VAR: Cache"
  debug: var=k8s.cache

- name: "VAR: OS Family"
  debug: var=ansible_os_family|lower

- name: "VAR: Required Packages"
  debug: var="{{ ansible_os_family|lower }}"
  # required_pkgs.{{ ansible_os_family|lower }}

- name: "VAR: Download Source"
  debug: var=source.url

- name: "VAR: Strict Checksum"
  debug: var=k8s.strict

- name: "VAR: Checksum"
  debug: var=source.checksum["{{ k8s.version }}"]

#- name: "VAR: Variable"
#  debug: var=rebar
