--- 
- debug: msg="Playbook source {{ playbook_source }} "

# debugging variables
- include: debug.yml
  when: debug

- name: install | Write kube-apiserver systemd init file
  template:
    src: "kube-apiserver.service.j2"
    dest: "/etc/systemd/system/kube-apiserver.service"
    backup: yes
  when: ansible_service_mgr == "systemd"
  notify: restart kube-apiserver

- name: install | Authorization config file
  template:
    src: "authorization-policy.jsonl.j2"
    dest: "{{ k8s.token_dir }}/authorization-policy.jsonl"
    backup: yes
  notify: restart kube-apiserver

- name: Populate users for token auth in API
  lineinfile:
    dest: "{{ k8s.token_dir }}/known_tokens.csv"
    create: yes
    line: '{{ item.value.pass }},{{ item.key }},{{ item.value.role }}'
    backup: yes
  with_dict: "{{ k8s.users }}"
  notify: restart kube-apiserver

- name: reload systemd
  command: systemctl daemon-reload

- name: reload kube-apiserver
  service:
    name: kube-apiserver
    state: restarted
    enabled: yes

- name: Enable apiserver
  service:
    name: kube-apiserver
    enabled: yes
    state: started

- meta: flush_handlers

- name: wait for the apiserver to be running
  wait_for:
    port: "{{ k8s.apiserver.insecure_port }}"
    timeout: 60

