--- 
- debug: msg="Playbook source {{ playbook_source }} "

# debugging variables
- include: debug.yml
  when: debug

- name: "Download Kubernetes Executables [SLOW]"
  get_url:
    dest: "{{bin_dir}}/kube-apiserver"
    checksum: "{{ item }}"
    url: "{{ source.url }}/kube-apiserver"
    validate_certs: yes
  with_items: "{{ vars['source']['checksum'][k8s.version]['kube-apiserver'] }}"
  when: source.checksum["{{k8s.version}}"] is defined and k8s.strict|default(true)

- name: install | Write kube-apiserver systemd init file
  template:
    src: "kube-apiserver.service.j2"
    dest: "/etc/systemd/system/kube-apiserver.service"
  when: ansible_service_mgr == "systemd"
  notify:
    - reload kube-apiserver systemd
    - restart kube-apiserver

- name: install | Authorization config file
  template:
    src: "authorization-policy.jsonl.j2"
    dest: "{{ k8s.token_dir }}/authorization-policy.jsonl"
  notify:
    - restart kube-apiserver

- name: Populate users for token auth in API
  lineinfile:
    dest: "{{ k8s.token_dir }}/known_tokens.csv"
    create: yes
    line: '{{ item.value.pass }},{{ item.key }},{{ item.value.role }}'
  with_dict: "{{ k8s.users }}"
  notify:
    - restart kube-apiserver

- name: Allow apiserver to bind on both secure and insecure ports
  shell: setcap cap_net_bind_service+ep {{ bin_dir }}/kube-apiserver
  changed_when: false

- meta: flush_handlers

- name: Enable apiserver
  service:
    name: kube-apiserver
    enabled: yes

- name: wait for the apiserver to be running
  wait_for:
    port: "{{ k8s.apiserver.insecure_port }}"
    timeout: 60

