--- 
- debug: msg="Playbook source {{ playbook_source }} "

- debug: msg="NOTE Staging Kubernetes Version {{k8s.version.stage}} for Upgrade from {{k8s.version}}"
  when:  not k8s.version == "{{k8s.version.stage | default(k8s.version)}}"

# debugging variables
- include: debug.yml
  when: debug
# main script

- include: ../shared/tasks/downloader.yml kube_component=kubectl kube_version={{k8s.version.stage | default(k8s.version)}}

# Put the kubectl in a reasonable place to be found by script and such.
- name: Copy kubectl to /usr/local/bin
  copy: remote_src=True src="{{bin_dir}}/kubectl" dest=/usr/local/bin/kubectl mode=0755

- name: Copy kubectl bash completion
  copy:
    src: kubectl_bash_completion.sh
    dest: /etc/bash_completion.d/kubectl.sh
  when: ansible_os_family in ["Debian","RedHat"]

